version : "3"
services :
  app:
    image: elmeddebyassmin/testdemo_project:1.2
    restart: on-failure
    ports:
      - 8085:8085
    depends_on:
      - mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
    stdin_open: true
    tty: true
    volumes:
      - "/Users/yassm/.m2:/root/.m2"
  mysqldb :
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE =test123
      - MYSQL_USER =root
      - MYSQL_PASSWORD =
      - MYSQL_ROOT_PASSWORD =
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
  .m2:

